def seed_database
  Propaganda.first_or_create(word: 'Bolsheviks', type: :noun)
  Propaganda.first_or_create(word: 'Bolshevik', type: :noun)
  Propaganda.first_or_create(word: 'Communist', type: :noun)
  Propaganda.first_or_create(word: 'Marxist', type: :noun)
  Propaganda.first_or_create(word: 'The West', type: :noun)
  Propaganda.first_or_create(word: 'Comrade', type: :noun)
  Propaganda.first_or_create(word: 'Lenin', type: :noun)
  Propaganda.first_or_create(word: 'Earth', type: :noun)
  Propaganda.first_or_create(word: 'Glavlit', type: :noun)
  Propaganda.first_or_create(word: 'Party line', type: :noun)
  Propaganda.first_or_create(word: 'petit-bourgeois', type: :noun)
  Propaganda.first_or_create(word: 'Agitprop', type: :noun)
  Propaganda.first_or_create(word: 'indoctrinate', type: :verb)
  Propaganda.first_or_create(word: 'eradicate', type: :verb)
  Propaganda.first_or_create(word: 'cleanse', type: :verb)
  Propaganda.first_or_create(word: 'censor', type: :verb)
  Propaganda.first_or_create(word: 'influence', type: :verb)
  Propaganda.first_or_create(word: 'with', type: :filler)
  Propaganda.first_or_create(word: 'for', type: :filler)
end
